In [1]:
from sqlalchemy import create_engine
import pandas as pd
import scipy.stats
from scipy.stats import ttest_ind
from scipy.stats import chi2_contingency

In [2]:
# connect to database
db_password = 'ma123456'
engine = create_engine(f'mysql+pymysql://root:{db_password}@localhost:3306/retail_ecom_db')

In [3]:
# Fetch data form view that contained clean data
query = 'SELECT * FROM v_clean_retail_ecom_data'

In [4]:
# put data in a dataframe
df = pd.read_sql(query, engine)
pd.set_option('display.max.columns', None)
df.sample(3)

,order_id,customer_id,customer_segment,customer_acquisition_date,customer_country,customer_state,customer_city,customer_zipcode,region,sku,product_category,product_subcategory,product_name,quantity,unit_price,unit_cost,gross_sales,discount_percent,discount_amount,net_sales,total_product_cost,order_profit,marketing_campaign,marketing_channel,marketing_cost_per_click,order_date,shipping_mode,shipping_date,delivery_date,actual_shipping_days,shipping_cost,shipping_charge_to_customer,payment_method,customer_satisfaction_score,order_returned
1251,ORD-101564,CUST-00150,budget conscious,2023-12-13,United States,California,San Francisco,94101,West,APPA-DENM-502,Apparel,Bottoms,Classic Slim-Fit Denim Jeans,1.0,88.0,22.0,88.0,0.1,8.8,79.2,22.0,57.2,NO_CAMP,Organic,0.00,2025-08-12,Standard,2025-08-14,2025-08-19,4,6.5,0.0,debit card,5.0,0
2562,ORD-103163,CUST-01098,budget conscious,2025-06-23,United States,California,San Francisco,94101,West,APPA-SHOE-504,Apparel,Footwear,Stratus Aero Running Shoes,3.0,120.0,35.0,360.0,0.1,36.0,324.0,105.0,219.0,CAMP_RETARGET_90,Display,0.15,2024-01-01,Overnight,2024-01-02,2024-01-03,1,14.5,0.0,apple pay,3.0,1
1749,ORD-102186,CUST-00784,budget conscious,2023-02-14,United States,Florida,Miami,33101,South,BEAU-SERM-701,Beauty & Personal Care,Skincare,HydraGlow Hyaluronic Acid Serum,1.0,35.0,4.5,35.0,0.0,0.0,35.0,4.5,30.5,CAMP_SUMMER_25,Email,0.05,2024-05-12,Economy,2024-05-13,2024-05-21,8,6.5,0.0,paypal,4.0,0

In [5]:
df.shape

(4255, 35)

# Hypothesis Testing

#### 1. Testing if the reason of marketing campaign [CAMP_BLACK_FRIDAY] having low profit is becasue of the high avg discount it has, that is larger than all avg dicounts of other campaign summed.

Using T-test to see if high avg discount is the actual reason

In [6]:
# Spliting into 2 groups: CAMP_BLACK_FRIDAY group and Other Campiagns Group
black_friday_cam_discounts = df[df['marketing_campaign'] == 'CAMP_BLACK_FRIDAY']['discount_amount']
other_cam_discounts = df[df['marketing_campaign'] != 'CAMP_BLACK_FRIDAY']['discount_amount']

In [7]:
# call T-test function and passing arguments
t_state, p_value = ttest_ind(black_friday_cam_discounts, other_cam_discounts)
print(f'T-statistic: {t_state}')
print(f'p-value: {p_value}')

T-statistic: 30.390071998624805
p-value: 9.419419751253906e-184

p-value = 9.41e-184 which is smaller than 0.05, that mean:
marketing campaign[CAMP_BLACK_FRIDAY] having low profit than other campaigns is because of high avg discount

#### 2. Apparel category has high return rate for all country and maybe it because size problem not shipping or one country problem, so here going to test if really Apparel has higher returnes than other categories

using Chi-Square because here seeing two categorical variables

In [8]:
# New column to categorize product category into Apparel and Other
# For easier analysis
df['product_category_group'] = df['product_category'].apply(
    lambda x: 'Apparel' if x == 'Apparel' else 'Other'
)
df.head(2)

,order_id,customer_id,customer_segment,customer_acquisition_date,customer_country,customer_state,customer_city,customer_zipcode,region,sku,product_category,product_subcategory,product_name,quantity,unit_price,unit_cost,gross_sales,discount_percent,discount_amount,net_sales,total_product_cost,order_profit,marketing_campaign,marketing_channel,marketing_cost_per_click,order_date,shipping_mode,shipping_date,delivery_date,actual_shipping_days,shipping_cost,shipping_charge_to_customer,payment_method,customer_satisfaction_score,order_returned,product_category_group
0,ORD-100000,CUST-00085,budget conscious,2024-06-05,United States,New York,New York,10001,East,BEAU-CREM-703,Beauty & Personal Care,Skincare,Ceramide Barrier Repair Night Cream,2.0,42.0,6.0,84.0,0.1,8.4,75.6,12.0,63.6,CAMP_RETARGET_90,Display,0.15,2025-10-29,Standard,2025-11-01,2025-11-05,4,8.0,0.0,credit card,NaN,0,Other
1,ORD-100002,CUST-01034,tech enthusiasts,2024-04-09,France,Île-de-France,Paris,75001,Europe,APPA-DENM-502,Apparel,Bottoms,Classic Slim-Fit Denim Jeans,5.0,88.0,22.0,440.0,0.0,0.0,440.0,110.0,330.0,CAMP_SUMMER_25,Email,0.05,2024-09-10,Standard,2024-09-12,2024-09-16,4,12.5,0.0,apple pay,4.0,0,Apparel

In [9]:
# creating cross table, because it is the argument accepted by chi-square function
contingency_table = pd.crosstab(df['product_category_group'], df['order_returned'])
contingency_table

order_returned             0    1
product_category_group
Apparel                  882  282
Other                   3032   59

In [10]:
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)
print(f'Chi-Square Statistic: {chi2_stat:.4f}')
print(f'p-value: {p_value}')
print(f'Degrees of Freedom: {dof:.4f}')
print(f'Expected Frequencies:\n', expected)

Chi-Square Statistic: 568.3082
p-value: 1.3101458080936257e-125
Degrees of Freedom: 1.0000
Expected Frequencies:
 [[1070.71586369   93.28413631]
 [2843.28413631  247.71586369]]

p-value < 0.05 then Apparel has higher return rate than other categories

but to test if it is really size problem not shipping, i am going to see if this problem affected by country or not

In [11]:
# checking the problem with Apparel is related to size issues or shipping
# isolating the information related to it, and specifing the column we want to check
apparel_category = df[df['product_category'] == 'Apparel'][['customer_country', 'order_returned']]
apparel_category.head()

   customer_country  order_returned
1            France               0
4     United States               0
7    United Kingdom               0
13    United States               0
14    United States               1

In [12]:
cross_table = pd.crosstab(apparel_category['customer_country'], apparel_category['order_returned'])
cross_table

order_returned      0    1
customer_country
Australia          55   21
Canada             92   35
France             72   16
Germany            89   21
United Kingdom    137   32
United States     437  157

In [21]:
chi2_stat, p_val, dof, expected = chi2_contingency(cross_table)
print(f'Chi-Square Statistic: {chi2_stat:.4f}')
print(f'p-value: {p_val}')
print(f'Degrees of Freedom: {dof:.4f}')
print(f'Expected Frequencies:\n', expected)

Chi-Square Statistic: 8.7305
p-value: 0.12030747340193465
Degrees of Freedom: 5.0000
Expected Frequencies:
 [[ 57.58762887  18.41237113]
 [ 96.23195876  30.76804124]
 [ 66.68041237  21.31958763]
 [ 83.35051546  26.64948454]
 [128.05670103  40.94329897]
 [450.09278351 143.90721649]]

p-value is greater than 0.05 which mean there is no correlation between returns and country, so it not shipping problem, it is sizing issue.

double checking, so testing with another column which is acutual days of shipping to see if there is a relation between returns and shipping days

In [22]:
apparel_categorys = df[df['product_category'] == 'Apparel'][['actual_shipping_days', 'order_returned']]
apparel_categorys.head()

    actual_shipping_days  order_returned
1                      4               0
4                      2               0
7                      3               0
13                     5               0
14                     4               1

In [24]:
cross_tab = pd.crosstab(apparel_categorys['actual_shipping_days'], apparel_categorys['order_returned'])
cross_tab

order_returned          0    1
actual_shipping_days
1                      24    8
2                     142   49
3                      60   19
4                     358  101
5                     134   34
6                      49   19
7                      75   29
8                      19    7
9                      19   13
10                      1    2
12                      1    0
16                      0    1

In [25]:
chi2_stat, p_val, dof, expected = chi2_contingency(cross_tab)
print(f'Chi-Square Statistic: {chi2_stat:.4f}')
print(f'p-value: {p_val}')
print(f'Degrees of Freedom: {dof:.4f}')
print(f'Expected Frequencies:\n', expected)

Chi-Square Statistic: 15.3650
p-value: 0.16638723452373347
Degrees of Freedom: 11.0000
Expected Frequencies:
 [[2.42474227e+01 7.75257732e+00]
 [1.44726804e+02 4.62731959e+01]
 [5.98608247e+01 1.91391753e+01]
 [3.47798969e+02 1.11201031e+02]
 [1.27298969e+02 4.07010309e+01]
 [5.15257732e+01 1.64742268e+01]
 [7.88041237e+01 2.51958763e+01]
 [1.97010309e+01 6.29896907e+00]
 [2.42474227e+01 7.75257732e+00]
 [2.27319588e+00 7.26804124e-01]
 [7.57731959e-01 2.42268041e-01]
 [7.57731959e-01 2.42268041e-01]]